name: "qunit__run-tests"
description: "Run QUnit browser tests using Karma"
inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "20"
  working-directory:
    description: "Directory containing package.json with Karma config"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm install

    - name: Run QUnit tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm test