# ═══════════════════════════════════════════════════════════════════════════════
# Phase_C__Test_Fixtures - Load test fixtures from JSON files
#
# Loads fixtures generated by Phase_B__Test_Data_Generator:
#   - fixture__simple.json
#   - fixture__multiple_wrappers.json
#   - fixture__nested_structure.json
#
# Place JSON files in same directory as this module, or set FIXTURES_DIR
# ═══════════════════════════════════════════════════════════════════════════════

import json
import os
from pathlib import Path
from typing  import Dict, List, Optional


# ═══════════════════════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════════════════════

# Directory containing fixture JSON files (default: same directory as this module)
FIXTURES_DIR = Path(__file__).parent

# Fixture names to load
FIXTURE_NAMES = ['simple', 'multiple_wrappers', 'nested_structure']


# ═══════════════════════════════════════════════════════════════════════════════
# Fixture Loading
# ═══════════════════════════════════════════════════════════════════════════════

def _load_fixture_from_json(name: str) -> Optional[dict]:
    """Load a single fixture from JSON file."""
    json_path = FIXTURES_DIR / f'fixture__{name}.json'

    if not json_path.exists():
        return None

    with open(json_path, 'r') as f:
        return json.load(f)


def _load_all_fixtures() -> Dict[str, dict]:
    """Load all fixtures from JSON files."""
    fixtures = {}

    for name in FIXTURE_NAMES:
        fixture = _load_fixture_from_json(name)
        if fixture:
            fixtures[name] = fixture

    return fixtures


# Load fixtures on module import
FIXTURES = _load_all_fixtures()


# ═══════════════════════════════════════════════════════════════════════════════
# Public API
# ═══════════════════════════════════════════════════════════════════════════════

def get_fixture(name: str) -> Optional[dict]:
    """Get a test fixture by name.

    Available fixtures: simple, multiple_wrappers, nested_structure

    Returns dict with:
    - name: Fixture name
    - html: Original HTML string
    - html_dict: Parsed dict with node_ids (Phase A output)
    - body_graph_json: Serialized body MGraph (Phase B output)

    Returns None if fixture not found.
    """
    return FIXTURES.get(name)


def get_html_dict(name: str) -> Optional[dict]:
    """Get just the html_dict for a fixture."""
    fixture = get_fixture(name)
    return fixture['html_dict'] if fixture else None


def get_body_graph_json(name: str) -> Optional[dict]:
    """Get just the body_graph_json for a fixture."""
    fixture = get_fixture(name)
    return fixture['body_graph_json'] if fixture else None


def list_fixtures() -> List[str]:
    """List available fixture names."""
    return list(FIXTURES.keys())


def reload_fixtures() -> None:
    """Reload fixtures from JSON files (useful after regeneration)."""
    global FIXTURES
    FIXTURES = _load_all_fixtures()


def get_fixtures_dir() -> Path:
    """Get the directory where fixture files are loaded from."""
    return FIXTURES_DIR


def set_fixtures_dir(path: str) -> None:
    """Set the directory to load fixture files from, then reload."""
    global FIXTURES_DIR, FIXTURES
    FIXTURES_DIR = Path(path)
    FIXTURES = _load_all_fixtures()


# ═══════════════════════════════════════════════════════════════════════════════
# Diagnostic Helpers
# ═══════════════════════════════════════════════════════════════════════════════

def check_fixtures_status() -> dict:
    """Check which fixtures are loaded and which files exist."""
    status = {
        'fixtures_dir': str(FIXTURES_DIR),
        'loaded': list(FIXTURES.keys()),
        'missing': [],
        'files': {}
    }

    for name in FIXTURE_NAMES:
        json_path = FIXTURES_DIR / f'fixture__{name}.json'
        exists = json_path.exists()
        status['files'][name] = {
            'path': str(json_path),
            'exists': exists
        }
        if not exists:
            status['missing'].append(name)

    return status


def print_fixtures_status() -> None:
    """Print diagnostic info about fixture loading."""
    status = check_fixtures_status()

    print(f"Fixtures Directory: {status['fixtures_dir']}")
    print(f"Loaded Fixtures: {status['loaded']}")

    if status['missing']:
        print(f"Missing Fixtures: {status['missing']}")
        print("\nTo generate fixtures, run in Phase B environment:")
        print("  python Phase_B__Test_Data_Generator.py")

    print("\nFile Status:")
    for name, info in status['files'].items():
        marker = "✓" if info['exists'] else "✗"
        print(f"  {marker} {name}: {info['path']}")