# ═══════════════════════════════════════════════════════════════════════════════
# Phase_C__Test_Data_Loader - Load test fixtures and reconstruct MGraph
# Use this in Phase C to load fixtures generated by Phase B
# ═══════════════════════════════════════════════════════════════════════════════

from mgraph_db.mgraph.MGraph import MGraph


def load_mgraph_from_json(graph_json: dict) -> MGraph:
    """Reconstruct an MGraph from serialized JSON.

    Args:
        graph_json: Dict from MGraph.json()

    Returns:
        Reconstructed MGraph instance
    """

    return MGraph.from_json(graph_json)


def load_fixture_for_transform(fixture: dict) -> tuple:
    """Load a fixture and prepare it for transformation testing.

    Args:
        fixture: Dict with html_dict and body_graph_json

    Returns:
        Tuple of (html_dict, mgraph) ready for testing
    """
    html_dict       = fixture['html_dict']
    body_graph_json = fixture['body_graph_json']

    mgraph = load_mgraph_from_json(body_graph_json)

    return html_dict, mgraph


def collect_node_ids_from_dict(node_dict: dict) -> set:
    """Recursively collect all node_ids from Html_Dict."""
    node_ids = set()

    if 'node_id' in node_dict:
        node_ids.add(node_dict['node_id'])

    for child in node_dict.get('nodes', []):
        if isinstance(child, dict):
            node_ids.update(collect_node_ids_from_dict(child))

    return node_ids


def collect_node_ids_from_mgraph(mgraph: MGraph) -> set:
    """Collect all node_ids from MGraph."""
    node_ids = set()

    for domain_node in mgraph.data().nodes():
        node_id = str(domain_node.node.data.node_id)
        node_ids.add(node_id)

    return node_ids