# ═══════════════════════════════════════════════════════════════════════════════
# Tests for Phase C - Full Pipeline Integration Tests
# Uses fixtures generated by Phase B - NO Phase A/B imports required
# ═══════════════════════════════════════════════════════════════════════════════

from unittest                               import TestCase
from Html_Use_Case__3__Source_Tracking      import Html_Use_Case__3__Source_Tracking
from Html_Dict__Helpers                     import (find_node_by_id          ,
                                                    unwrap_element_in_dict   ,
                                                    merge_adjacent_text_nodes,
                                                    html_dict_to_html        )
from Phase_C__Test_Fixtures                 import get_fixture, get_html_dict, get_body_graph_json
from Phase_C__Test_Data_Loader              import (load_mgraph_from_json       ,
                                                    load_fixture_for_transform  ,
                                                    collect_node_ids_from_dict  ,
                                                    collect_node_ids_from_mgraph)
from mgraph_db.mgraph.MGraph                import MGraph
from osbot_utils.testing.__                 import __


class test_Phase_C__Full_Pipeline_Integration(TestCase):

    # ═══════════════════════════════════════════════════════════════════════════
    # Test 1: Node_Ids Flow Through Pipeline (Phase A → B → C)
    # ═══════════════════════════════════════════════════════════════════════════

    def test_1__node_ids_present_in_html_dict(self):             # Verify html_dict has node_ids (Phase A output).
        html_dict = get_html_dict('simple')

        dict_node_ids = collect_node_ids_from_dict(html_dict)

        assert len(dict_node_ids) > 0, "Dict should have node_ids"
        assert dict_node_ids == {'f0000001',
                                 'f0000002',
                                 'f0000003',
                                 'f0000004',
                                 'f0000005',
                                 'f0000006',
                                 'f0000007'}
        assert dict_node_ids != {'PLACEHOLDER_b_001',
                                 'PLACEHOLDER_body_001',
                                 'PLACEHOLDER_div_001',
                                 'PLACEHOLDER_html_001',
                                 'PLACEHOLDER_text_001',
                                 'PLACEHOLDER_text_002',
                                 'PLACEHOLDER_text_003'}

    def test_1b__node_ids_present_in_mgraph(self):  # Verify MGraph has node_ids (Phase B output).
        body_graph_json = get_body_graph_json('simple')

        assert type(body_graph_json) is dict
        assert body_graph_json       != {}

        mgraph          = load_mgraph_from_json(body_graph_json)

        assert type(mgraph) is MGraph
        assert mgraph.export().to__mgraph_json() != {'edges': {},
                                                     'graph_data': None,
                                                     'graph_id': mgraph.graph.graph_id(),
                                                     'graph_path': None,
                                                     'graph_type': None,
                                                     'index_config': None,
                                                     'nodes': {},
                                                     'schema_types': None}
        mgraph_node_ids = collect_node_ids_from_mgraph(mgraph)



        assert len(mgraph_node_ids) > 0, "MGraph should have node_ids"
        assert mgraph.graph.model.data.nodes.obj() == __(c0000003=__(node_data=None,
                                                                     node_path=None,
                                                                     node_type='mgraph_db.mgraph.schemas.Schema__MGraph__Node.Schema__MGraph__Node',
                                                                     node_id='c0000003'),
                                                         f0000002=__(node_data=None,
                                                                     node_path='body',
                                                                     node_type='mgraph_db.mgraph.schemas.Schema__MGraph__Node.Schema__MGraph__Node',
                                                                      node_id='f0000002'),
                                                       f0000003=__(node_data=None,
                                                                   node_path='body.div',
                                                                   node_type='mgraph_db.mgraph.schemas.Schema__MGraph__Node.Schema__MGraph__Node',
                                                                   node_id='f0000003'),
                                                       f0000004=__(node_data=__(value_type='builtins.str',
                                                                                value='Hello ',
                                                                                key='f0000003:0'),
                                                                   node_id='f0000004',
                                                                   node_type='mgraph_db.mgraph.schemas.Schema__MGraph__Node__Value.Schema__MGraph__Node__Value',
                                                                   node_path='text'),
                                                       f0000005=__(node_data=None,
                                                                   node_path='body.div.b',
                                                                   node_type='mgraph_db.mgraph.schemas.Schema__MGraph__Node.Schema__MGraph__Node',
                                                                   node_id='f0000005'),
                                                       f0000006=__(node_data=__(value_type='builtins.str',
                                                                                value='World',
                                                                                key='f0000005:0'),
                                                                   node_id='f0000006',
                                                                   node_type='mgraph_db.mgraph.schemas.Schema__MGraph__Node__Value.Schema__MGraph__Node__Value',
                                                                   node_path='text'),
                                                       f0000007=__(node_data=__(value_type='builtins.str',
                                                                                value='!',
                                                                                key='f0000003:2'),
                                                                   node_id='f0000007',
                                                                   node_type='mgraph_db.mgraph.schemas.Schema__MGraph__Node__Value.Schema__MGraph__Node__Value',
                                                                   node_path='text'))

    def test_1c__node_ids_match_between_dict_and_mgraph(self):
        """Verify node_ids from dict appear in MGraph (Phase A → B connection)."""
        fixture = get_fixture('simple')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        dict_node_ids   = collect_node_ids_from_dict(html_dict)
        mgraph_node_ids = collect_node_ids_from_mgraph(mgraph)

        # Body-related node_ids should overlap
        # (html_dict includes head, mgraph is just body)
        body_dict = html_dict['nodes'][0] if html_dict.get('nodes') else html_dict
        for node in html_dict.get('nodes', []):
            if isinstance(node, dict) and node.get('tag') == 'body':
                body_dict = node
                break

        body_dict_ids = collect_node_ids_from_dict(body_dict)
        common_ids = body_dict_ids & mgraph_node_ids

        assert len(common_ids) > 0, "MGraph should reuse node_ids from dict"

    def test_1d__node_ids_in_tracking_data_match_original(self):
        """Node_ids in tracking data should match original dict."""
        fixture = get_fixture('multiple_wrappers')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        wrapper_mapping = transformer.get_all_wrapper_mappings()
        dict_node_ids = collect_node_ids_from_dict(html_dict)

        for wrapper_id in wrapper_mapping.keys():
            assert wrapper_id in dict_node_ids, f"Wrapper {wrapper_id} should be from original dict"

    # ═══════════════════════════════════════════════════════════════════════════
    # Test 2: Wrapper Mapping Captures Inline Elements
    # ═══════════════════════════════════════════════════════════════════════════

    def test_2__wrapper_mapping_captures_inline_elements(self):
        """wrapper_mapping should contain entries for <a>, <b>, <i> etc."""
        fixture = get_fixture('multiple_wrappers')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        wrapper_mapping = transformer.get_all_wrapper_mappings()

        assert len(wrapper_mapping) >= 2, f"Should have at least 2 wrappers (a, b), got {len(wrapper_mapping)}"

    def test_2b__wrapper_mapping_has_correct_structure(self):
        """Each wrapper entry should have parent_id and child_id."""
        fixture = get_fixture('simple')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        wrapper_mapping = transformer.get_all_wrapper_mappings()

        for wrapper_id, info in wrapper_mapping.items():
            assert 'parent_id' in info, f"Wrapper {wrapper_id} missing parent_id"
            assert 'child_id'  in info, f"Wrapper {wrapper_id} missing child_id"
            assert type(info['parent_id']) is str
            assert type(info['child_id'])  is str

    def test_2c__wrapper_ids_exist_in_original_dict(self):
        """wrapper_id values should be findable in original Html_Dict."""
        fixture = get_fixture('multiple_wrappers')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        wrapper_mapping = transformer.get_all_wrapper_mappings()

        for wrapper_id in wrapper_mapping.keys():
            node, parent, index = find_node_by_id(html_dict, wrapper_id)
            assert node is not None, f"Wrapper {wrapper_id} not found in original dict"
            assert 'tag' in node, f"Wrapper {wrapper_id} should be an element node"

    # ═══════════════════════════════════════════════════════════════════════════
    # Test 3: Source Mapping Captures Merged Text Nodes
    # ═══════════════════════════════════════════════════════════════════════════

    def test_3__source_mapping_captures_merged_text_nodes(self):
        """source_mapping should map merged node to original text node_ids."""
        fixture = get_fixture('multiple_wrappers')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        source_mapping = transformer.get_all_source_mappings()

        assert len(source_mapping) >= 1, "Should have merged text nodes"

    def test_3b__source_mapping_contains_multiple_sources(self):
        """Each merged node should have 2+ source node_ids."""
        fixture = get_fixture('multiple_wrappers')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        source_mapping = transformer.get_all_source_mappings()

        for merged_id, source_ids in source_mapping.items():
            assert len(source_ids) >= 2, f"Merged {merged_id} should have 2+ sources, got {len(source_ids)}"
            for source_id in source_ids:
                assert type(source_id) is str

    def test_3c__source_ids_exist_in_original_dict(self):
        """source node_ids should be findable in original Html_Dict."""
        fixture = get_fixture('simple')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        source_mapping = transformer.get_all_source_mappings()

        for merged_id, source_ids in source_mapping.items():
            for source_id in source_ids:
                node, parent, index = find_node_by_id(html_dict, source_id)
                assert node is not None, f"Source {source_id} not found in original dict"

    # ═══════════════════════════════════════════════════════════════════════════
    # Test 4: Can Trace Back to Original Html_Dict
    # ═══════════════════════════════════════════════════════════════════════════

    def test_4__can_find_wrapper_in_dict(self):
        """Should be able to locate wrapper element in original dict."""
        fixture = get_fixture('simple')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        wrapper_mapping = transformer.get_all_wrapper_mappings()

        for wrapper_id, info in wrapper_mapping.items():
            node, parent, index = find_node_by_id(html_dict, wrapper_id)

            assert node   is not None, f"Should find wrapper {wrapper_id}"
            assert parent is not None, f"Wrapper should have parent"
            assert index  is not None, f"Wrapper should have index in parent"

            tag = node.get('tag', '').lower()
            assert tag in {'a', 'b', 'i', 'span', 'strong', 'em'}, f"Expected inline tag, got {tag}"

    def test_4b__can_find_text_sources_in_dict(self):
        """Should be able to locate source text nodes in original dict."""
        fixture = get_fixture('simple')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        source_mapping = transformer.get_all_source_mappings()

        for merged_id, source_ids in source_mapping.items():
            for source_id in source_ids:
                node, parent, index = find_node_by_id(html_dict, source_id)

                assert node is not None, f"Should find source {source_id}"
                assert node.get('type') == 'TEXT', f"Source should be TEXT node"

    # ═══════════════════════════════════════════════════════════════════════════
    # Test 5: Unwrap Elements to Produce Clean HTML (Phase E Preview)
    # ═══════════════════════════════════════════════════════════════════════════

    def test_5__unwrap_single_element(self):
        """Unwrapping single element should preserve children."""
        fixture = get_fixture('simple')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        wrapper_mapping = transformer.get_all_wrapper_mappings()

        # Unwrap all wrappers
        for wrapper_id in wrapper_mapping.keys():
            result = unwrap_element_in_dict(html_dict, wrapper_id)
            assert result is True, f"Should unwrap {wrapper_id}"

        # Convert back to HTML
        output_html = html_dict_to_html(html_dict)

        # Should not contain <b> tag anymore
        assert '<b>' not in output_html, f"Should not have <b> tag: {output_html}"
        assert 'World' in output_html, f"Should preserve text content: {output_html}"

    def test_5b__unwrap_multiple_elements(self):
        """Unwrapping multiple elements should produce clean HTML."""
        fixture = get_fixture('multiple_wrappers')
        html_dict, mgraph = load_fixture_for_transform(fixture)

        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        wrapper_mapping = transformer.get_all_wrapper_mappings()

        # Unwrap all wrappers
        for wrapper_id in wrapper_mapping.keys():
            unwrap_element_in_dict(html_dict, wrapper_id)

        # Merge adjacent text nodes
        merge_adjacent_text_nodes(html_dict)

        # Convert back to HTML
        output_html = html_dict_to_html(html_dict)

        # Should not contain inline tags
        assert '<a>' not in output_html.lower(), f"Should not have <a>: {output_html}"
        assert '<b>' not in output_html.lower(), f"Should not have <b>: {output_html}"

        # Should preserve all text
        assert 'Start'  in output_html
        assert 'link'   in output_html
        assert 'middle' in output_html
        assert 'bold'   in output_html
        assert 'end'    in output_html

    def test_5c__full_workflow_nested_structure(self):
        """Full workflow with nested HTML structure."""
        fixture           = get_fixture('nested_structure')
        input_html        = fixture.get('html')

        html_dict, mgraph = load_fixture_for_transform(fixture)

        # Phase C: Transform with tracking
        transformer = Html_Use_Case__3__Source_Tracking()
        transformer.transform_mgraph(mgraph)

        # Get tracking data
        wrapper_mapping = transformer.get_all_wrapper_mappings()
        source_mapping  = transformer.get_all_source_mappings()

        # Verify we captured wrappers (a, b, i)
        assert len(wrapper_mapping) >= 3, f"Should have 3+ wrappers, got {len(wrapper_mapping)}"

        # Unwrap all inline elements
        for wrapper_id in wrapper_mapping.keys():
            unwrap_element_in_dict(html_dict, wrapper_id)

        # Merge adjacent text nodes
        merge_adjacent_text_nodes(html_dict)

        # Convert back to HTML
        output_html = html_dict_to_html(html_dict)

        # Verify clean output
        assert '<a'  not in output_html.lower()
        assert '<i'  not in output_html.lower()

        # Verify text preserved
        assert 'link' in output_html
        assert 'bold' in output_html

        assert input_html  == ('<!DOCTYPE html>\n'
                               '<html>\n'
                               '    <body>\n'
                               '        <div>\n'
                               '            This is a <a href="">link</a> with some <b>bold</b> in the mix\n'
                               '        </div>\n'
                               '        <div>\n'
                               '            this is the <i>2nd div</i> in here\n'
                               '        </div>\n'
                               '    </body>\n'
                               '</html>\n')
        assert output_html == ('<html><body><div>\n'
                               '            This is a link with some bold in the mix\n'
                               '        </div><div>\n'
                               '            this is the 2nd div in here\n'
                               '        </div></body></html>')